# Generated by Django 4.1.1 on 2022-12-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kshavarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('family', models.CharField(blank=True, max_length=50, null=True)),
                ('father', models.CharField(blank=True, max_length=50, null=True)),
                ('kodMele', models.IntegerField(blank=True, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('kodEshtrak', models.IntegerField(blank=True, null=True)),
                ('ctiy', models.CharField(blank=True, max_length=50, null=True)),
                ('licenseNumber', models.IntegerField(blank=True, null=True)),
                ('dateRegistration', models.DateTimeField()),
                ('activiityStatus', models.CharField(blank=True, max_length=100, null=True)),
                ('rosta', models.CharField(blank=True, max_length=100, null=True)),
                ('river', models.CharField(blank=True, max_length=100, null=True)),
                ('chahak', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
